const META_TYPES = {
  TICKET_ACEITO: "TICKET_ACEITO",
  TICKET_NEGADO: "TICKET_NEGADO",
  REVISAO: "REVISAO",
  BAN: "BAN",
  DENUNCIA: "DENUNCIA",
  BAN_HACK: "BAN_HACK"
};

module.exports = { META_TYPES };